// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package io.github.lvbo.lct.protobuf;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated string course = 4;</code>
     * @return A list containing the course.
     */
    java.util.List<java.lang.String>
        getCourseList();
    /**
     * <code>repeated string course = 4;</code>
     * @return The count of course.
     */
    int getCourseCount();
    /**
     * <code>repeated string course = 4;</code>
     * @param index The index of the element to return.
     * @return The course at the given index.
     */
    java.lang.String getCourse(int index);
    /**
     * <code>repeated string course = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the course at the given index.
     */
    com.google.protobuf.ByteString
        getCourseBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      email_ = "";
      course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                course_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              course_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          course_ = course_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.lvbo.lct.protobuf.StudentOuterClass.Student.class, io.github.lvbo.lct.protobuf.StudentOuterClass.Student.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList course_;
    /**
     * <code>repeated string course = 4;</code>
     * @return A list containing the course.
     */
    public com.google.protobuf.ProtocolStringList
        getCourseList() {
      return course_;
    }
    /**
     * <code>repeated string course = 4;</code>
     * @return The count of course.
     */
    public int getCourseCount() {
      return course_.size();
    }
    /**
     * <code>repeated string course = 4;</code>
     * @param index The index of the element to return.
     * @return The course at the given index.
     */
    public java.lang.String getCourse(int index) {
      return course_.get(index);
    }
    /**
     * <code>repeated string course = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the course at the given index.
     */
    public com.google.protobuf.ByteString
        getCourseBytes(int index) {
      return course_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < course_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, course_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < course_.size(); i++) {
          dataSize += computeStringSizeNoTag(course_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCourseList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.lvbo.lct.protobuf.StudentOuterClass.Student)) {
        return super.equals(obj);
      }
      io.github.lvbo.lct.protobuf.StudentOuterClass.Student other = (io.github.lvbo.lct.protobuf.StudentOuterClass.Student) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getCourseList()
          .equals(other.getCourseList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getCourseCount() > 0) {
        hash = (37 * hash) + COURSE_FIELD_NUMBER;
        hash = (53 * hash) + getCourseList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.lvbo.lct.protobuf.StudentOuterClass.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Student)
        io.github.lvbo.lct.protobuf.StudentOuterClass.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.lvbo.lct.protobuf.StudentOuterClass.Student.class, io.github.lvbo.lct.protobuf.StudentOuterClass.Student.Builder.class);
      }

      // Construct using io.github.lvbo.lct.protobuf.StudentOuterClass.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        email_ = "";

        course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Student_descriptor;
      }

      @java.lang.Override
      public io.github.lvbo.lct.protobuf.StudentOuterClass.Student getDefaultInstanceForType() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.Student.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.lvbo.lct.protobuf.StudentOuterClass.Student build() {
        io.github.lvbo.lct.protobuf.StudentOuterClass.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.lvbo.lct.protobuf.StudentOuterClass.Student buildPartial() {
        io.github.lvbo.lct.protobuf.StudentOuterClass.Student result = new io.github.lvbo.lct.protobuf.StudentOuterClass.Student(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.age_ = age_;
        result.email_ = email_;
        if (((bitField0_ & 0x00000001) != 0)) {
          course_ = course_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.course_ = course_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.lvbo.lct.protobuf.StudentOuterClass.Student) {
          return mergeFrom((io.github.lvbo.lct.protobuf.StudentOuterClass.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.lvbo.lct.protobuf.StudentOuterClass.Student other) {
        if (other == io.github.lvbo.lct.protobuf.StudentOuterClass.Student.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.course_.isEmpty()) {
          if (course_.isEmpty()) {
            course_ = other.course_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCourseIsMutable();
            course_.addAll(other.course_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.lvbo.lct.protobuf.StudentOuterClass.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.lvbo.lct.protobuf.StudentOuterClass.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCourseIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          course_ = new com.google.protobuf.LazyStringArrayList(course_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string course = 4;</code>
       * @return A list containing the course.
       */
      public com.google.protobuf.ProtocolStringList
          getCourseList() {
        return course_.getUnmodifiableView();
      }
      /**
       * <code>repeated string course = 4;</code>
       * @return The count of course.
       */
      public int getCourseCount() {
        return course_.size();
      }
      /**
       * <code>repeated string course = 4;</code>
       * @param index The index of the element to return.
       * @return The course at the given index.
       */
      public java.lang.String getCourse(int index) {
        return course_.get(index);
      }
      /**
       * <code>repeated string course = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the course at the given index.
       */
      public com.google.protobuf.ByteString
          getCourseBytes(int index) {
        return course_.getByteString(index);
      }
      /**
       * <code>repeated string course = 4;</code>
       * @param index The index to set the value at.
       * @param value The course to set.
       * @return This builder for chaining.
       */
      public Builder setCourse(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseIsMutable();
        course_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string course = 4;</code>
       * @param value The course to add.
       * @return This builder for chaining.
       */
      public Builder addCourse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCourseIsMutable();
        course_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string course = 4;</code>
       * @param values The course to add.
       * @return This builder for chaining.
       */
      public Builder addAllCourse(
          java.lang.Iterable<java.lang.String> values) {
        ensureCourseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, course_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string course = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCourse() {
        course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string course = 4;</code>
       * @param value The bytes of the course to add.
       * @return This builder for chaining.
       */
      public Builder addCourseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCourseIsMutable();
        course_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Student)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Student)
    private static final io.github.lvbo.lct.protobuf.StudentOuterClass.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.lvbo.lct.protobuf.StudentOuterClass.Student();
    }

    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.lvbo.lct.protobuf.StudentOuterClass.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WeatherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Weather)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 query = 1;</code>
     * @return The query.
     */
    int getQuery();

    /**
     * <code>.tutorial.Weather.Season season = 2;</code>
     * @return The enum numeric value on the wire for season.
     */
    int getSeasonValue();
    /**
     * <code>.tutorial.Weather.Season season = 2;</code>
     * @return The season.
     */
    io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season getSeason();
  }
  /**
   * Protobuf type {@code tutorial.Weather}
   */
  public static final class Weather extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Weather)
      WeatherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Weather.newBuilder() to construct.
    private Weather(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Weather() {
      season_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Weather();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Weather(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              query_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              season_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Weather_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Weather_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.class, io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Builder.class);
    }

    /**
     * Protobuf enum {@code tutorial.Weather.Season}
     */
    public enum Season
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SPRING = 0;</code>
       */
      SPRING(0, 0),
      /**
       * <code>SUMMER = 1;</code>
       */
      SUMMER(1, 1),
      /**
       * <code>FALL = 2;</code>
       */
      FALL(2, 2),
      /**
       * <code>WINTER = 3;</code>
       */
      WINTER(4, 3),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>AUTUMN = 2;</code>
       */
      public static final Season AUTUMN = FALL;
      /**
       * <code>SPRING = 0;</code>
       */
      public static final int SPRING_VALUE = 0;
      /**
       * <code>SUMMER = 1;</code>
       */
      public static final int SUMMER_VALUE = 1;
      /**
       * <code>FALL = 2;</code>
       */
      public static final int FALL_VALUE = 2;
      /**
       * <code>AUTUMN = 2;</code>
       */
      public static final int AUTUMN_VALUE = 2;
      /**
       * <code>WINTER = 3;</code>
       */
      public static final int WINTER_VALUE = 3;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Season valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Season forNumber(int value) {
        switch (value) {
          case 0: return SPRING;
          case 1: return SUMMER;
          case 2: return FALL;
          case 3: return WINTER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Season>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Season> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Season>() {
              public Season findValueByNumber(int number) {
                return Season.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (index == -1) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.getDescriptor().getEnumTypes().get(0);
      }

      private static final Season[] VALUES = getStaticValuesArray();
      private static Season[] getStaticValuesArray() {
        return new Season[] {
          SPRING, SUMMER, FALL, AUTUMN, WINTER, 
        };
      }
      public static Season valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Season(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Weather.Season)
    }

    public static final int QUERY_FIELD_NUMBER = 1;
    private int query_;
    /**
     * <code>int32 query = 1;</code>
     * @return The query.
     */
    @java.lang.Override
    public int getQuery() {
      return query_;
    }

    public static final int SEASON_FIELD_NUMBER = 2;
    private int season_;
    /**
     * <code>.tutorial.Weather.Season season = 2;</code>
     * @return The enum numeric value on the wire for season.
     */
    @java.lang.Override public int getSeasonValue() {
      return season_;
    }
    /**
     * <code>.tutorial.Weather.Season season = 2;</code>
     * @return The season.
     */
    @java.lang.Override public io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season getSeason() {
      @SuppressWarnings("deprecation")
      io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season result = io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season.valueOf(season_);
      return result == null ? io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (query_ != 0) {
        output.writeInt32(1, query_);
      }
      if (season_ != io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season.SPRING.getNumber()) {
        output.writeEnum(2, season_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (query_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, query_);
      }
      if (season_ != io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season.SPRING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, season_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.lvbo.lct.protobuf.StudentOuterClass.Weather)) {
        return super.equals(obj);
      }
      io.github.lvbo.lct.protobuf.StudentOuterClass.Weather other = (io.github.lvbo.lct.protobuf.StudentOuterClass.Weather) obj;

      if (getQuery()
          != other.getQuery()) return false;
      if (season_ != other.season_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery();
      hash = (37 * hash) + SEASON_FIELD_NUMBER;
      hash = (53 * hash) + season_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.lvbo.lct.protobuf.StudentOuterClass.Weather prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Weather}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Weather)
        io.github.lvbo.lct.protobuf.StudentOuterClass.WeatherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Weather_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Weather_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.class, io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Builder.class);
      }

      // Construct using io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        query_ = 0;

        season_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.internal_static_tutorial_Weather_descriptor;
      }

      @java.lang.Override
      public io.github.lvbo.lct.protobuf.StudentOuterClass.Weather getDefaultInstanceForType() {
        return io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.lvbo.lct.protobuf.StudentOuterClass.Weather build() {
        io.github.lvbo.lct.protobuf.StudentOuterClass.Weather result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.lvbo.lct.protobuf.StudentOuterClass.Weather buildPartial() {
        io.github.lvbo.lct.protobuf.StudentOuterClass.Weather result = new io.github.lvbo.lct.protobuf.StudentOuterClass.Weather(this);
        result.query_ = query_;
        result.season_ = season_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.lvbo.lct.protobuf.StudentOuterClass.Weather) {
          return mergeFrom((io.github.lvbo.lct.protobuf.StudentOuterClass.Weather)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.lvbo.lct.protobuf.StudentOuterClass.Weather other) {
        if (other == io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.getDefaultInstance()) return this;
        if (other.getQuery() != 0) {
          setQuery(other.getQuery());
        }
        if (other.season_ != 0) {
          setSeasonValue(other.getSeasonValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.lvbo.lct.protobuf.StudentOuterClass.Weather parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.lvbo.lct.protobuf.StudentOuterClass.Weather) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int query_ ;
      /**
       * <code>int32 query = 1;</code>
       * @return The query.
       */
      @java.lang.Override
      public int getQuery() {
        return query_;
      }
      /**
       * <code>int32 query = 1;</code>
       * @param value The query to set.
       * @return This builder for chaining.
       */
      public Builder setQuery(int value) {
        
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuery() {
        
        query_ = 0;
        onChanged();
        return this;
      }

      private int season_ = 0;
      /**
       * <code>.tutorial.Weather.Season season = 2;</code>
       * @return The enum numeric value on the wire for season.
       */
      @java.lang.Override public int getSeasonValue() {
        return season_;
      }
      /**
       * <code>.tutorial.Weather.Season season = 2;</code>
       * @param value The enum numeric value on the wire for season to set.
       * @return This builder for chaining.
       */
      public Builder setSeasonValue(int value) {
        
        season_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.tutorial.Weather.Season season = 2;</code>
       * @return The season.
       */
      @java.lang.Override
      public io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season getSeason() {
        @SuppressWarnings("deprecation")
        io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season result = io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season.valueOf(season_);
        return result == null ? io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season.UNRECOGNIZED : result;
      }
      /**
       * <code>.tutorial.Weather.Season season = 2;</code>
       * @param value The season to set.
       * @return This builder for chaining.
       */
      public Builder setSeason(io.github.lvbo.lct.protobuf.StudentOuterClass.Weather.Season value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        season_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.tutorial.Weather.Season season = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeason() {
        
        season_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Weather)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Weather)
    private static final io.github.lvbo.lct.protobuf.StudentOuterClass.Weather DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.lvbo.lct.protobuf.StudentOuterClass.Weather();
    }

    public static io.github.lvbo.lct.protobuf.StudentOuterClass.Weather getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Weather>
        PARSER = new com.google.protobuf.AbstractParser<Weather>() {
      @java.lang.Override
      public Weather parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Weather(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Weather> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Weather> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.lvbo.lct.protobuf.StudentOuterClass.Weather getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Weather_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Weather_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\010tutorial\"C\n\007Student\022\014\n\004" +
      "name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022\016" +
      "\n\006course\030\004 \003(\t\"\212\001\n\007Weather\022\r\n\005query\030\001 \001(" +
      "\005\022(\n\006season\030\002 \001(\0162\030.tutorial.Weather.Sea" +
      "son\"F\n\006Season\022\n\n\006SPRING\020\000\022\n\n\006SUMMER\020\001\022\010\n" +
      "\004FALL\020\002\022\n\n\006AUTUMN\020\002\022\n\n\006WINTER\020\003\032\002\020\001B\035\n\033i" +
      "o.github.lvbo.lct.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Student_descriptor,
        new java.lang.String[] { "Name", "Age", "Email", "Course", });
    internal_static_tutorial_Weather_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Weather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Weather_descriptor,
        new java.lang.String[] { "Query", "Season", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
